sudo: false

language: python

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

python:
    - 3.5
    - 3.6

# Install packages
install:
    - sudo apt-get update
    - source activate install_miniconda.sh
    - source activate test-environment
    - pip install coveralls
    - pip install coverage
    - pip install codecov
#    - python setup.py install

script:
    - conda build --quiet .
    - coverage run setup.py test

after_success:
    - coveralls
    - codecov
